blog/api/urls.py
from django.urls import path
from blog.api import views

urlpatterns = [
    path('posts/', views.PostListAPIView.as_view(), name='api-post-list'),
    path('post/new/', views.PostCreateAPIView.as_view(), name='api-post-new'),
    path('post/<int:pk>/', views.PostDetailAPIView.as_view(), name='api-post-detail'),
    path('post/<int:pk>/update/', views.PostUpdateDeleteAPIView.as_view(), name='api-post-update'),
    path('post/<int:pk>/delete/', views.PostUpdateDeleteAPIView.as_view(), name='api-post-delete'),
    path('search/', views.SearchAPIView.as_view(), name='api-search'),
    path('user_posts/', views.UserPostListView.as_view(), name='api-user-posts'),
    path('saved-posts/', views.SavedPostsAPIView.as_view(), name='api-all-save'),
    path('my-posts/', views.UserPostListView.as_view(), name='api-user-post'),

]

blog/urls.py
from django.urls import path
from . import views
from .views import (AllSaveView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, 
                    SaveView, UserPostListView, LikeView, LikeCommentView, posts_of_following_profiles, AllLikeView)

urlpatterns = [
    path('home/', views.first, name='firsthome'),
    path('', PostListView.as_view(), name='blog-home'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/like/', LikeView, name='post-like'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('post/save/', SaveView, name='post-save'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.search, name='search'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from . import api
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    
    path('accounts/', include('allauth.urls')),
    
    path('', include('blog.urls')),
    path('user/', include('users.urls')),
    path('notifications/', include('notification.urls')),
    path('chats/', include('chat.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
] + api.urlpatterns


urlpatterns += staticfiles_urlpatterns()

notification/urls.py
from django.urls import path
from notification.views import ShowNotifications

urlpatterns = [
    path('', ShowNotifications, name='show-notifications'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

# I wrote this code


class Post(models.Model):
    """ Post model """
    title = models.CharField(max_length=150)
    content = RichTextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="blogpost", blank=True)
    saves = models.ManyToManyField(User, related_name="blogsave", blank=True)
    image = models.ImageField(upload_to='blog_pics', blank=True, null=True)

    def total_likes(self):
        return self.likes.count()

    def total_saves(self):
        return self.saves.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk": self.pk})


class Comment(models.Model):
    """ Comment model """
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="blogcomment", blank=True)
    reply = models.ForeignKey('self', null=True, related_name="replies", on_delete=models.CASCADE)

    def total_clikes(self):
        return self.likes.count()

    def __str__(self):
        return '%s - %s - %s' % (self.post.title, self.name, self.id)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk": self.pk})
# end of code I wrote

notification/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# I wrote this code
class Notification(models.Model):
    """ Notification model """
    NOTIFICATION_TYPES = ((1, 'Like'), (2, 'Follow'), (3, 'Comment'),
                          (4, 'Reply'), (5, 'Like-Comment'), (6, 'Like-Reply'))

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='notify_post', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_from_user')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_to_user')
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=120, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s - %s - %s - %s' % (self.id, self.post, self.sender, self.user, self.notification_type)
# end of code I wrote

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control custom-txt', 'cols': '40', 'rows': '3'}), label='')

    class Meta:
        model = Comment
        fields = ['body',]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from PIL import Image

# I wrote this code
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    image = forms.ImageField(label=('Image'), error_messages={'invalid': ("Image files only")}, 
                             widget=forms.FileInput, required=False)

    class Meta:
        model = Profile
        fields = ['bio', 'date_of_birth', 'image',]

    """Saving Cropped Image"""

    def save(self, *args, **kwargs):
        img = super(ProfileUpdateForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x and y and w and h:
            image = Image.open(img.image)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
            resized_image.save(img.image.path)

        return img
    
# end of code I wrote

blog/api/views.py
from rest_framework.generics import ListAPIView
from ..models import Post
from .serializers import PostSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.db.models import Q

# I wrote this code


class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostCreateAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # Get the author from the request.
        author = request.user
        req_data = request.data

        # Create a new post instance.
        post = Post.objects.create(
            title=req_data.get('title'),
            content=req_data.get('content'),
            author=author,
        )

        # Save the post instance.
        post.save()
        serializer = PostSerializer(post)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class PostDetailAPIView(APIView):

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        serializer = PostSerializer(post)
        return Response(serializer.data, status=status.HTTP_200_OK)


class PostUpdateDeleteAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        serializer = PostSerializer(post)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request, pk):
        # Get the post instance.
        post = get_object_or_404(Post, pk=pk)

        # Check if the authenticated user is the author of the post.
        if post.author != request.user:
            raise PermissionDenied(
                'You are not authorized to update this post.')

        # Get the new data from the request.
        data = request.data

        # Check if the title and content are provided.
        if not data.get('title') or not data.get('content'):
            return Response('Title and content must be provided.', status=status.HTTP_400_BAD_REQUEST)

        # Update the post instance.
        post.title = data.get('title')
        post.content = data.get('content')
        post.save()
        serializer = PostSerializer(post)

        return Response(serializer.data, status=status.HTTP_200_OK)

    def delete(self, request, pk):
        # Get the post instance.
        post = get_object_or_404(Post, pk=pk)

        if post.author != request.user:
            raise PermissionDenied(
                'You are not authorized to update this post.')

        # Delete the post instance.
        post.delete()

        return Response(status=204)


class SearchAPIView(APIView):
    def get(self, request):
        query = self.request.query_params.get('query')

        if not query:
            return Response([], status=status.HTTP_200_OK)

        # Perform a case-insensitive search for both title and username
        posts = Post.objects.filter(
            Q(title__icontains=query) | Q(author__username__icontains=query)
        )

        # Serialize the search results
        serializer = PostSerializer(posts, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)


class UserPostListView(ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):
        username = self.request.query_params.get('username')
        return Post.objects.filter(author__username=username).order_by('-date_posted')


class UserPostsAPIView(ListAPIView):
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        my_posts = Post.objects.filter(author=user)
        return my_posts


class SavedPostsAPIView(ListAPIView):
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        saved_posts = user.blogsave.all()
        return saved_posts

# end of code I wrote

notification/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from notification.models import Notification
from .serializers import NotificationSerializer


class ShowNotificationsAPIView(APIView):
    def get(self, request):
        user = request.user
        notifications = Notification.objects.filter(user=user).order_by('-date')
        serializer = NotificationSerializer(notifications, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

notification/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from notification.models import Notification


""" All notifications """


@login_required
def ShowNotifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    context = {
        'notifications': notifications,
    }
    return render(request, 'blog/notifications.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}About{% endblock %}

{% block content %}

<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1>About page</h1>
        <br>
        <p>Made with &#128150; by Ronik Bhattacharjee &#9996;</p>
    </div>
</div>


{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>CMedia | {% block title %}{% endblock %}</title>
</head>
<body>
    <header class="site-header">

        <!-- NAVBAR -->
        {% include 'blog/navbar.html' %}
    </header>

    <!-- MAIN SECTION -->
    <main role="main" class="container">
      <div class="row">

          <!-- MESSAGES -->
          <div class="col-md-8 m-auto">
            {% if messages %}
              {% for message in messages %}
                <div class="alert {{ message.tags }}">
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}           
          </div>

          
          {% block content %}{% endblock %}
          

      </div>
    </main>

    <!-- SCRIPTS -->
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous"></script>
      
      <script>
        $(function () {
    
          /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
          $("#id_image").change(function () {
            if (this.files && this.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $("#image").attr("src", e.target.result);
                $("#modalCrop").modal('show');
              }
              reader.readAsDataURL(this.files[0]);
            }
          });
    
          /* SCRIPTS TO HANDLE THE CROPPER BOX */
          var $image = $("#image");
          var cropBoxData;
          var canvasData;
          $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
              viewMode: 1,
              aspectRatio: 1/1,
              minCropBoxWidth: 200,
              minCropBoxHeight: 200,
              ready: function () {
                $image.cropper("setCanvasData", canvasData);
                $image.cropper("setCropBoxData", cropBoxData);
              }
            });
          }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
            location.reload();
          });
    
          $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
          });
    
          $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
          });
    
          /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
          $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            // console.log(cropData);
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
          });
    
        });
      </script>

      <script type="text/javascript">

        $(document).ready(function(event){
          
          // $("#chat-box").scrollTop($("#chat-box")[0].scrollHeight);

          // LIKE POSTS

          $(document).on('click','#like',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-like" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#like-section').html(response['form']);
                  console.log($('#like-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT LIKE

          $(document).on('click','.clike',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: "{% url 'comment-like' %}",
              data: {'id':pk, 'pid':'{{post.pk}}', 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('.main-comment-section').html(response['form']);
                  console.log($('.main-comment-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // SAVE POSTS

          $(document).on('click','#save',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-save" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#save-section').html(response['form']);
                  console.log($('#save-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT FORM

          $(document).on('submit','.comment-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

          // REPLY FORM

          $(document).on('submit','.reply-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

        });


      </script>

      {% block script %}{% endblock %}

</body>
</html>

blog/templates/blog/comments.html
<div id="tempocs">


{% if user.is_authenticated %}
    <form class="comment-form" method="post" action=".">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class=" mb-4">Add Comment</legend>
            <textarea required style="width: 100%;" name="body" id="cmtbody" cols="40" rows="5"></textarea>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" id="acsubmit" type="submit">Add Comment</button>
        </div>
    </form>
{% endif %}

<br>

<h3>Comments ({{ comments.count }}) :</h3>
<hr>
<br>
{% if not comments %}
    No Comments Yet...
{% else %}
    
    {% for comment in comments %}

    <div class="content-section">
        <div class="media g-mb-30 media-comment">
            <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15 rounded-circle article-img" src="{{comment.name.profile.image.url}}" alt="Profile-image">
            <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                <div class="g-mb-15">
                    <h5 class="h5 g-color-gray-dark-v1 mb-0"><a class="mr-2" href="{% url 'profile-detail-view' comment.name.pk %}">{{comment.name}}</a></h5>
                    <small class="text-mute">{{comment.date_added}}</small>
                </div>
                
                <p class="mt-3">{{comment.body}}</p>
            
                <ul class="list-inline d-sm-flex my-0">
                    <li class="list-inline-item g-mr-20">
                        <form action="{% url 'comment-like' %}" method="POST">
                            {% csrf_token %}
                            
                            {% if user.is_authenticated %}
                                {% for key, value in clikes.items %}
                                    {% if key == comment.id %}
                                        {% if value == True %}
                                            <button type="submit" name="comment_id" value="{{comment.id}}" class="btn btnhrt clike"><i class="fas fa-heart"></i></button>
                                        {% else %}
                                            <button type="submit" name="comment_id" value="{{comment.id}}" class="btn btnhrt clike"><i class="far fa-heart"></i></button>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <button class="btn btnhrt"><i class="far fa-heart"></i></button>
                            {% endif %}

                             {{comment.total_clikes}}
                        </form>
                    </li>
                    <li class="list-inline-item">
                        &nbsp;&nbsp;&nbsp;
                        <a class="btn btncmt" data-toggle="collapse" href="#multiCollapse{{comment.id}}" role="button" aria-expanded="false" aria-controls="multiCollapse{{comment.id}}">
                            <i class="far fa-comment"></i>
                        </a>
                         {{comment.replies.count}}
                    </li>
                </ul>

                <br>

                <div class="collapse multi-collapse" id="multiCollapse{{comment.id}}">
                <hr>
                    {% if user.is_authenticated %}
                        <form class="reply-form" method="POST" action=".">
                            {% csrf_token %}
                            <input type="hidden" name="comment_id" value="{{comment.id}}">
                            <fieldset class="form-group">
                                <legend class="h5 mb-4">Replies :</legend>
                                <textarea required style="width: 100%;" name="body" id="cmt-body" cols="40" rows="2"></textarea>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Reply</button>
                            </div>
                        </form>
                    {% endif %}

                    {% for reply in comment.replies.all %}
                    <br>
                        <div class="g-mb-15">
                            <h5 class="h5 g-color-gray-dark-v1 mb-0"><a class="mr-2" href="{% url 'profile-detail-view' reply.name.pk %}">{{reply.name}}</a></h5>
                            <small class="text-mute">{{reply.date_added}}</small>
                        </div>
                        
                        <p class="mt-3">{{reply.body}}</p>

                        <ul class="list-inline d-sm-flex my-0">
                            <li class="list-inline-item g-mr-20">
                                
                                <form action="{% url 'comment-like' %}" method="POST">
                                    {% csrf_token %}
                                
                                    {% if user.is_authenticated %}
                                        {% for key, value in clikes.items %}
                                            {% if reply.id == key %}
                                                {% if value == True %}
                                                    <button type="submit" name="comment_id" value="{{reply.id}}" class="btn btnhrt clike"><i class="fas fa-heart"></i></button>
                                                {% else %}
                                                    <button type="submit" name="comment_id" value="{{reply.id}}" class="btn btnhrt clike"><i class="far fa-heart"></i></button>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <button class="btn btnhrt"><i class="far fa-heart"></i></button>
                                    {% endif %}
                                
                                        {{reply.total_clikes}}
                                </form>
                            </li>
                        </ul>
                        <hr>
                    {% endfor %}
                    

                </div>

            </div>
        </div>
    </div>
    <br>

    {% endfor %}
{% endif %}

</div>

blog/templates/blog/first.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- ADDITIONAL STYLING -->

<style>
  body{
    background-color: #fff;
  }
</style>

<div>
    
    <!-- Page Hero-->
    <section class=" page-header page-header-light bg-white mt-4 container">
      <div class="page-header-content pt-5">
          <div class="container">
              <div class="row align-items-center">
                  <div class="col-lg-6 " data-aos="fade-up">
                      <h1 style="" class="page-header-title font-weight-bold">Let’s Wow your online presence</h1>
                      <br>
                      <p class="page-header-text mb-5">
                        Surround yourself with people who are going to lift you higher. Join today and share your thoughts.
                        <br><br>
                        Designed and developed by <a target="_blank" href="https://github.com/Ronik22">Ronik Bhattacharjee</a>
                      </p>

                      {% if user.is_authenticated %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="{% url 'posts-follow-view' %}">Get Started</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="#"><i class="far fa-check-circle"></i>&nbsp;LOGGED IN</a>
                      {% else %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="{% url 'register' %}">REGISTER</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="{% url 'account_login' %}">LOGIN</a>
                      {% endif %}
                  </div>
                  <div class="col-lg-6 d-none d-lg-block" data-aos="fade-up" data-aos-delay="100"><img class="img-fluid" src="/static/blog/images/undraw_social_interaction_cy9i.png" /></div>
              </div>
          </div>
      </div>
      <br>
    </section>

</div>

{% endblock %}